# Generated by Django 3.0.3 on 2021-05-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fl_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_status',
            name='Doctor_user',
            field=models.ForeignKey(limit_choices_to={'user_designation': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
