# Generated by Django 3.0.3 on 2021-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_user', '0002_auto_20210613_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_status',
            name='duration',
            field=models.CharField(blank=True, default='Audio Not Uploaded', max_length=100),
        ),
    ]
