# Generated by Django 3.0.3 on 2021-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_user', '0003_job_status_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_status',
            name='feedback',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job_status',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
