# Generated by Django 3.2.5 on 2021-07-18 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fl_user', '0004_auto_20210702_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_status',
            name='expiration_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='job_status',
            name='assign_first_level_user',
            field=models.ForeignKey(limit_choices_to={'user_designation': 'first level user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_level_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job_status',
            name='assign_second_level_user',
            field=models.ForeignKey(limit_choices_to={'user_designation': 'second level user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_level_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
